name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Verify Azure Resources
      run: |
        echo "Listing resource groups..."
        az group list --query "[].name" -o tsv
        
        echo "Listing public IPs in resource group..."
        az network public-ip list --resource-group "t-clo-901-nts-0-item" --query "[].name" -o tsv
    
    - name: Get DB Host
      id: dbhost
      run: |
        echo "Attempting to get IP address..."
        DB_HOST=$(az network public-ip show \
          --resource-group "t-clo-901-nts-0-item" \
          --name "ubuntu-vm-nts-0-bdd" \
          --query ipAddress \
          -o tsv)
        
        if [ -z "$DB_HOST" ]; then
          echo "Failed to get IP address. Setting default value..."
          DB_HOST="xxx.xxx.xxx.xxx"  # Valeur par défaut ou IP statique si vous en avez une
        fi
        
        echo "DB_HOST=$DB_HOST"
        echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Docker image
      env:
        DB_HOST: ${{ env.DB_HOST }}
      run: |
        echo "Building with DB_HOST=$DB_HOST"
        docker build \
          --build-arg DB_CONNECTION=${{ vars.DB_CONNECTION }} \
          --build-arg DB_HOST=${{ env.DB_HOST }} \
          --build-arg DB_PORT=${{ vars.DB_PORT }} \
          --build-arg DB_DATABASE=${{ vars.DB_DATABASE }} \
          --build-arg DB_USERNAME=${{ vars.DB_USERNAME }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -t tistech0/countersepitechapp:latest \
          -t tistech0/countersepitechapp:${{ github.sha }} .
        docker push tistech0/countersepitechapp:latest
        docker push tistech0/countersepitechapp:${{ github.sha }}