name: Mirror CI and Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mirror:
    name: Build, Push Docker Image and Mirror Repository
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Étape 2 : Vérifier les fichiers nécessaires
      - name: Verify required files
        run: |
          test -f .env.tmpl || (echo ".env.tmpl is missing" && exit 1)
          test -d public || (echo "public directory is missing" && exit 1)

      # Étape 3 : Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t countersepitechapp:latest .

      # Étape 4 : Vérifier l'image Docker
      - name: Verify Docker Image
        run: |
          docker images | grep countersepitechapp || (echo "Docker image not built" && exit 1)
          docker run --rm countersepitechapp:latest ls /var/www/html/public || (echo "Public directory not found in container" && exit 1)

      # Étape 5 : Pousser l'image vers Docker Hub (ou autre registre)
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag countersepitechapp:latest epitechmscpropromo2025/countersepitechapp:latest
          docker push epitechmscpropromo2025/countersepitechapp:latest

      # Étape 6 : Pousser les fichiers vers le dépôt miroir
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2025/T-CLO-901-NAN_10.git
          ssh_private_key: ${{ secrets.SSH_KEY }}
